PROYECTO_ROL6/Models/ErrorViewModel.cs
namespace PROYECTO_ROL6.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PROYECTO_ROL6/Models/Usuario.cs
namespace PROYECTO_ROL6.Models
{
    public class Usuario
    {
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Clave { get; set; }
        public string [] Roles { get; set; }

    }
}

PROYECTO_ROL6/Controllers/AccesoController.cs
using Microsoft.AspNetCore.Mvc;

using PROYECTO_ROL6.Models;
using PROYECTO_ROL6.Data;

namespace PROYECTO_ROL6.Controllers
{
    public class AccesoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Index(Usuario _usuario)
        {
            DA_Logica _da_logica = new DA_Logica();

            string nombre = _da_logica.validarUsuario(_usuario.Correo, _usuario.Clave);
            return View();
        }
    }
}

PROYECTO_ROL6/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PROYECTO_ROL6.Models;
using System.Diagnostics;

namespace PROYECTO_ROL6.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Ventas()
        {
            return View();
        }

        public IActionResult Compras()
        {
            return View();
        }

        public IActionResult Clientes()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PROYECTO_ROL6/Views/Acceso/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <div class="row mt-5">
        <div class="col-sm-4 offset-sm-4">
            <form asp-controller="Acceso" asp-action="Index" method="post">
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Email</label>
                    <input type="email" class="form-control" aria-describedby="emailHelp">
                    
                </div>
                <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">Contraseña</label>
                    <input type="password" class="form-control">
                </div>
                
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
    </div>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

PROYECTO_ROL6/Views/Home/Clientes.cshtml
@{
    ViewData["Title"] = "Clientes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <div class="alert alert-success">
        <h2 class="display-4">Esta en la vista Clientes</h2>
    </div>
</div>

PROYECTO_ROL6/Views/Home/Compras.cshtml
@{
    ViewData["Title"] = "Compras";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <div class="alert alert-success">
        <h2 class="display-4">Esta en la vista Compras</h2>
    </div>
</div>

PROYECTO_ROL6/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <div class="alert alert-success">
        <h2 class="display-4">Esta en la vista Index</h2>
    </div>
</div>

PROYECTO_ROL6/Views/Home/Ventas.cshtml
@{
    ViewData["Title"] = "Ventas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <div class="alert alert-success">
        <h2 class="display-4">Esta en la vista Ventas</h2>
    </div>
</div>

PROYECTO_ROL6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PROYECTO_ROL6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PROYECTO_ROL6.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PROYECTO_ROL6</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Ventas">Ventas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Compras">Compras</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Clientes">Clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PROYECTO_ROL6 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>